name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.23.0
  firebase_auth: 3.10.0
  cloud_firestore: 3.4.9
  firebase_storage: 10.3.9
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.1.0+1
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  syncfusion_flutter_datepicker: 20.3.48
  flutter:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
