// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGIzBGs7tnlCq1UAvNjbzvzR-4O6ty_J4',
    appId: '1:1065255062969:web:dcc870ad54a5160cdd3a68',
    messagingSenderId: '1065255062969',
    projectId: 'presensi-8501e',
    authDomain: 'presensi-8501e.firebaseapp.com',
    storageBucket: 'presensi-8501e.appspot.com',
    measurementId: 'G-FRDTLW8YGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQs3Juk45BJZJqCxLUt-_knljS2MYaT1s',
    appId: '1:1065255062969:android:c2359a8040bcc920dd3a68',
    messagingSenderId: '1065255062969',
    projectId: 'presensi-8501e',
    storageBucket: 'presensi-8501e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpT3KSkPvJHe2njSZfywmK1JN9TCY0fo',
    appId: '1:1065255062969:ios:649193f1ff1d05e2dd3a68',
    messagingSenderId: '1065255062969',
    projectId: 'presensi-8501e',
    storageBucket: 'presensi-8501e.appspot.com',
    androidClientId: '1065255062969-qcnj6egu3ob0l4t5q60tts11r0eqnv4r.apps.googleusercontent.com',
    iosClientId: '1065255062969-et5ats4hod31m1bd7vmfjgpmfqfgddmi.apps.googleusercontent.com',
    iosBundleId: 'com.unustudents.presensi',
  );
}
